spring.datasource.url=jdbc:mysql://localhost:3306/tutoring_center?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Root@123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.training.centermanagement.entity
mybatis.configuration.map-underscore-to-camel-case=true

logging.level.com.training.centermanagement.mapper=debug